
title: TechBrown - A SysAdmin Blog
email: techbrown@hotmail.com
description: TechBrown is a sysAdmin blog dedicated to Linux and Windows how to guides, tutorials and resources.
baseurl: ""
url: "https://www.tuxwp.com"
twitter:
  username: techbrown_com
github:
  username:  gopalraha
logo: "https://cdn.techbrown.com/wp-content/uploads/2017/05/favicon.gif"
webmaster_verifications:
  google: bhuezyxBc3SKo52oYsC1lvq5Oz8Y6Lv1UFlYzkgEe5U  
  bing: B63DE33935FFC536F2E68610359E4F5C
  
permalink: :title.shtml

paginate_path: "/page/:num/"
paginate: 12

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
